-- =============================================================================
-- Storage: bucket service-photos (Supabase Dashboard o CLI)
-- =============================================================================
-- 1) Crea el bucket en Dashboard → Storage → New bucket
--    - Name: service-photos
--    - Public bucket: ON (para URLs públicas en la app)
-- 2) Recomendado en el mismo modal:
--    - Restrict file size: ON (ej. 5 MB)
--    - Restrict MIME types: ON → image/jpeg, image/png, image/webp
-- 3) Aplica la migración 0038 (supabase db push): políticas en storage.objects
--    sin ALTER TABLE (en hosted Supabase no eres owner de storage.objects).
--
-- Si la subida falla con "new row violates row-level security policy",
-- ejecuta 0038 o revisa que tu usuario tenga role admin/super_admin en profiles.
--
-- Bucket `avatars` (app móvil Expo, foto de perfil): migración 0041 crea el bucket
-- y políticas. El primer segmento de la ruta del archivo DEBE ser el UUID del usuario
-- (auth.uid), por ejemplo `550e8400-.../1730000000.jpg`. Si renombras esa carpeta
-- en el panel (p. ej. a "user pfp"), las subidas desde la app fallarán por RLS.
-- =============================================================================

-- Opcional: crear bucket por SQL (puede requerir permisos de superuser en local)
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('service-photos', 'service-photos', true)
-- ON CONFLICT (id) DO NOTHING;
