#!/bin/bash
# Verify database state and sync issues

echo "=== RESERVATIONS DATABASE AUDIT ==="
echo ""
echo "1. Checking reservation statuses..."
pg_isready -h localhost -p 5432 > /dev/null 2>&1 && echo "✓ Local DB running" || echo "✗ Local DB not running"

echo ""
echo "2. Data integrity checks needed via Supabase:"
echo "   - Run in Supabase SQL Editor:"
echo ""
echo "-- Show all service data"
echo "SELECT id, name, description, is_active FROM public.services LIMIT 10;"
echo ""
echo "-- Show all service options with prices"
echo "SELECT id, service_id, name, base_price, currency_code, image_url FROM public.service_options LIMIT 10;"
echo ""
echo "-- Show reservations"
echo "SELECT id, public_reference, status, total_amount, currency_code FROM public.reservations LIMIT 10;"
echo ""
echo "-- Check admin profile status"
echo "SELECT id, email, role FROM public.profiles WHERE email = 'admin@reservapro.com';"
echo ""
echo "-- Test RPC functions exist"
echo "SELECT proname FROM pg_proc WHERE proname LIKE 'admin_create%';"
echo ""
echo ""
echo "=== WHAT TO DO NOW ==="
echo "1. Kill all Node servers:"
echo "   killall node"
echo ""
echo "2. Clear any browser cache:"
echo "   - Chrome: Cmd+Shift+Delete → Clear cache"
echo ""
echo "3. Restart dev servers:"
echo "   Terminal 1: npm run dev --prefix admin-app"
echo "   Terminal 2: npm run dev --prefix client-app"
echo ""
echo "4. Restart expo app (if needed)"
echo ""
echo "5. Test in this order:"
echo "   a) Dashboard - should show correct USD amounts"
echo "   b) Reservations page - should show list with 4 states"
echo "   c) Create service - should upload photo without RLS error"
echo "   d) User app - should show correct prices ($250, $1200, etc)"
echo ""
